### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by seirdotexe** [LolHacksRule/AngryBirdsFlashStuff#2]
I created a [simple script](https://github.com/seirdotexe/secureswf-mapper) that may be useful to your project.

**Comment by LolHacksRule** [comment]
Thank you so much! I was previously using a script on Zenhax to deobfuscate Breakfast's symbol names but it doesn't seem to deobfuscate some values correctly, biggest one are enums which however are properly detected by your script, nice work!

**Comment by seirdotexe** [comment]
You're welcome. Is there perhaps a Discord server related to Angry Birds development? Maybe one you're in too?

**Comment by LolHacksRule** [comment]
The Angry Birds Modding Hub is a server I'm both the main admin to and constantly active in discussing and starting conversations of modding Angry Birds games or general conversations.
